
-- @SqlSnippetPriority 100

-- The following source code ("Code") may only be used in accordance with the terms
-- and conditions of the license agreement you have with IBM Corporation. The Code 
-- is provided to you on an "AS IS" basis, without warranty of any kind.  
-- SUBJECT TO ANY STATUTORY WARRANTIES WHICH CAN NOT BE EXCLUDED, IBM MAKES NO 
-- WARRANTIES OR CONDITIONS EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED 
-- TO, THE IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A 
-- PARTICULAR PURPOSE, AND NON-INFRINGEMENT, REGARDING THE CODE. IN NO EVENT WILL 
-- IBM BE LIABLE TO YOU OR ANY PARTY FOR ANY DIRECT, INDIRECT, SPECIAL OR OTHER 
-- CONSEQUENTIAL DAMAGES FOR ANY USE OF THE CODE, INCLUDING, WITHOUT LIMITATION, 
-- LOSS OF, OR DAMAGE TO, DATA, OR LOST PROFITS, BUSINESS, REVENUE, GOODWILL, OR 
-- ANTICIPATED SAVINGS, EVEN IF IBM HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH 
-- DAMAGES. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF 
-- INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY 
-- NOT APPLY TO YOU.




-- Notes
-- MDM_TODO:  statements are placed in the generated SQL file when user changes are required.
-- 1. Edit the following SQL files following any associated instructions.
-- 2. Connect to the database.
-- 3. Run each SQL file as shown below and in the same order.
--          db2 -vf Rollback_PartyAddressExtension_MetaData_DB2.sql
--          db2 -vf Rollback_PartyAddressExtension_CONSTRAINTS_DB2.sql
--          db2 -vf Rollback_PartyAddressExtension_TRIGGERS_DB2.sql
--          db2 -vf Rollback_PartyAddressExtension_SETUP_DB2.sql
--#SET TERMINATOR ;


DELETE FROM db2admin.GROUPTXMAP WHERE ENTITY_TX_MAP_ID >= 1000000 AND ENTITY_TX_MAP_ID <= 1009999;

DELETE FROM db2admin.EXTSETCONDVAL WHERE EXTSET_CONDVAL_ID >= 1000000 AND EXTSET_CONDVAL_ID <= 1009999;
DELETE FROM db2admin.CDCONDITIONVALTP WHERE COND_VAL_TP_CD >= 1000000 AND COND_VAL_TP_CD <= 1009999;
DELETE FROM db2admin.EXTENSIONSET WHERE EXTENSION_SET_ID >= 1000000 AND EXTENSION_SET_ID <= 1009999;
DELETE FROM db2admin.BUSINTERNALTXN WHERE BUS_INTERN_TXN_ID >= 1000000 AND BUS_INTERN_TXN_ID <= 1009999;
DELETE FROM db2admin.INTERNALTXREQRESP WHERE INTERNTX_REQRESP_ID >= 1000000 AND INTERNTX_REQRESP_ID <= 1009999;
DELETE FROM db2admin.INTERNALTXNKEY WHERE INTERN_TX_KEY_ID >= 1000000 AND INTERN_TX_KEY_ID <= 1009999;
DELETE FROM db2admin.CDINTERNALTXNTP WHERE INTERNAL_BUS_TX_TP >= 1000000 AND INTERNAL_BUS_TX_TP <= 1009999;
DELETE FROM db2admin.BUSINESSTXREQRESP WHERE BUSTX_REQRESP_ID >= 1000000 AND BUSTX_REQRESP_ID <= 1009999;
DELETE FROM db2admin.EXTERNALTXNKEY WHERE EXTERN_TX_KEY_ID >= 1000000 AND EXTERN_TX_KEY_ID <= 1009999;
DELETE FROM db2admin.CDBUSINESSTXTP WHERE BUSINESS_TX_TP_CD >= 1000000 AND BUSINESS_TX_TP_CD <= 1009999;
DELETE FROM db2admin.V_ELEMENTATTRIBUTE WHERE V_ELEMENT_ATTRB_ID >= 1000000 AND V_ELEMENT_ATTRB_ID <= 1009999;
DELETE FROM db2admin.V_ELEMENT WHERE GROUP_NAME IN ('XAddressBObjExt');
DELETE FROM db2admin.GROUPDWLTABLE WHERE GROUP_DWLTABLE_ID >= 1000000 AND GROUP_DWLTABLE_ID <= 1009999;
DELETE FROM db2admin.V_GROUP WHERE GROUP_NAME IN ('XAddressBObjExt');
DELETE FROM db2admin.CDDWLCOLUMNTP WHERE DWLCOLUMN_TP_CD >= 1000000 AND DWLCOLUMN_TP_CD <= 1009999;
DELETE FROM db2admin.CDDWLTABLETP WHERE DWLTABLE_TP_CD >= 1000000 AND DWLTABLE_TP_CD <= 1009999;
DELETE FROM db2admin.ERRREASON WHERE ERR_REASON_TP_CD >= 1000000 AND ERR_REASON_TP_CD <= 1009999;
DELETE FROM db2admin.CDERRMESSAGETP WHERE ERR_MESSAGE_TP_CD >= 1000000 AND ERR_MESSAGE_TP_CD <= 1009999;
DELETE FROM db2admin.COMPONENTTYPE WHERE COMPONENT_TYPE_ID >= 1000000 AND COMPONENT_TYPE_ID <= 1009999;
DELETE FROM db2admin.STANDARDIZER WHERE STANDARDIZER_ID >= 1000000 AND STANDARDIZER_ID <= 1009999;

DELETE FROM db2admin.ASIDEFINITION WHERE ASI_DEFINITION_ID >= 1000000 AND ASI_DEFINITION_ID <= 1009999;
